### ISSUE TITLE
Panic coming from running `cloud-tabs`

### ISSUE THREAD

**Issue by alexwlchan** [alexwlchan/safari.rs#23]
This is wrong:

```console
$ safari --version
safari v2.0.1

$ safari icloud-tabs
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Spotted on my iMac logged into my personal iCloud account.

Backtrace isn’t particularly helpful:

```console
$ set -x RUST_BACKTRACE 1; safari icloud-tabs
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: safari::main
  10: std::panicking::try::do_call
  11: __rust_maybe_catch_panic
  12: std::rt::lang_start
```

**Comment by alexwlchan** [comment]
Possibly of note: the `--list-devices` verb doesn't panic, but anything that prints URLs does.
